export const EDITOR_UPDATE_VALUE = 'EDITOR_UPDATE_VALUE';
export const MENU_UPDATE_STYLE = 'MENU_UPDATE_STYLE';
export const SIDE_MENU_UPDATE_STYLE = 'SIDE_MENU_UPDATE_STYLE';
export const SIDE_MENU_UPDATE_HIDDEN_STATUS = 'SIDE_MENU_UPDATE_HIDDEN_STATUS';
export const SIDE_MENU_UPDATE_MOUSE_IN_STATUS = 'SIDE_MENU_UPDATE_MOUSE_IN_STATUS';
export const SIDE_MENU_UPDATE_EXPANDED_STATUS = 'SIDE_MENU_UPDATE_EXPANDED_STATUS';
export const ON_EDITOR_KEY_UP = 'ON_EDITOR_KEY_UP';
export const ON_EDITOR_CLICK = 'ON_EDITOR_CLICK';