export const SIDE_MENU_UPDATE_STYLE = 'SIDE_MENU_UPDATE_STYLE';
export const SIDE_MENU_UPDATE_HIDDEN_STATUS = 'SIDE_MENU_UPDATE_HIDDEN_STATUS';
export const SIDE_MENU_UPDATE_MOUSE_IN_STATUS = 'SIDE_MENU_UPDATE_MOUSE_IN_STATUS';
export const SIDE_MENU_UPDATE_EXPANDED_STATUS = 'SIDE_MENU_UPDATE_EXPANDED_STATUS';